name = "Salinger"
license = "MIT"
licenselink = "https://github.com/jacksalici/salinger/blob/master/LICENSE"
description = "A minimal but powerful hugo theme."
homepage = "jacksalici.com/salinger-hugo-theme"
tags = ["simple", "minimal", "clean", "fast", "blog", "portfolio", "responsive", "twemoji", "recursion", "section"]
features = ["fast", "blog", "sorting", "dark mode", "categories"]
min_version = "0.87.0"

[author]
  name = "Jack Salici"
  homepage = "jacksalici.com"



